name: Lint

on: [push]

jobs:
  python:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11", "3.12"]
        linter: ["mypy", "ruff", "pylint", "black --check"]
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip poetry
        poetry install

    - name: ${{ matrix.linter }}
      run: poetry run ${{ matrix.linter }} $(git ls-files '*.py')
